# Writes src/LandaDoc.Shared/Locations/LocationData.g.cs: every country (ISO 3166-1, English and
# French names, from the pycountry package) and, for the countries in provinces-and-towns.json,
# their provinces and main towns.
#
#   python -m pip install pycountry
#   python tools/locations/generate.py
import gettext
import json
import os
import pycountry

here = os.path.dirname(os.path.abspath(__file__))
out = os.path.join(here, '..', '..', 'src', 'LandaDoc.Shared', 'Locations', 'LocationData.g.cs')

fr = gettext.translation('iso3166-1', pycountry.LOCALES_DIR, languages=['fr'])

# ISO's names are formal ("Congo, The Democratic Republic of the"); use everyday names instead
overrides = {
    'BO': ('Bolivia', 'Bolivie'),
    'CD': ('Democratic Republic of the Congo', 'République démocratique du Congo'),
    'CG': ('Republic of the Congo', 'République du Congo'),
    'CI': ("Côte d'Ivoire", "Côte d'Ivoire"),
    'FM': ('Micronesia', 'Micronésie'),
    'GB': ('United Kingdom', 'Royaume-Uni'),
    'IR': ('Iran', 'Iran'),
    'KP': ('North Korea', 'Corée du Nord'),
    'KR': ('South Korea', 'Corée du Sud'),
    'LA': ('Laos', 'Laos'),
    'MD': ('Moldova', 'Moldavie'),
    'PS': ('Palestine', 'Palestine'),
    'RE': ('Réunion', 'La Réunion'),
    'VI': ('U.S. Virgin Islands', 'Îles Vierges des États-Unis'),
    'RU': ('Russia', 'Russie'),
    'SY': ('Syria', 'Syrie'),
    'TW': ('Taiwan', 'Taïwan'),
    'TZ': ('Tanzania', 'Tanzanie'),
    'US': ('United States', 'États-Unis'),
    'VA': ('Vatican City', 'Vatican'),
    'VE': ('Venezuela', 'Venezuela'),
    'VN': ('Vietnam', 'Viêt Nam'),
}

def cs(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

countries = []
for c in pycountry.countries:
    en = getattr(c, 'common_name', None) or c.name
    french = fr.gettext(c.name)
    # The French list is in index order ("Salomon, Îles"); put it back in reading order
    if ', Île' in french:
        name, island = french.split(', ', 1)
        french = f'{island} {name}'.replace(' (Keeling)', '').replace(' (Falkland)', '')
    if c.alpha_2 in overrides:
        en, french = overrides[c.alpha_2]
    countries.append((c.alpha_2, en, french))
countries.sort(key=lambda c: c[0])

data = json.load(open(os.path.join(here, 'provinces-and-towns.json'), encoding='utf-8'))
data.pop('_comment', None)
known = {c[0] for c in countries}
for code in data:
    assert code in known, f'{code} in provinces-and-towns.json is not an ISO country code'

lines = [
    '// <auto-generated>',
    '// Written by tools/locations/generate.py from ISO 3166-1 (pycountry) and',
    '// tools/locations/provinces-and-towns.json. Edit those and run the script; don\'t edit this file.',
    '// </auto-generated>',
    'namespace LandaDoc.Shared.Locations;',
    '',
    'public static partial class Locations',
    '{',
    '    private static readonly Country[] AllCountries =',
    '    [',
]
lines += [f'        new({cs(code)}, {cs(en)}, {cs(french)}),' for code, en, french in countries]
lines += ['    ];', '', '    private static readonly Dictionary<string, Province[]> ProvinceData = new()', '    {']
for code in sorted(data):
    lines.append(f'        [{cs(code)}] =')
    lines.append('        [')
    for province in sorted(data[code], key=str.casefold):
        towns = ', '.join(cs(t) for t in data[code][province])
        lines.append(f'            new({cs(province)}, [{towns}]),')
    lines.append('        ],')
lines += ['    };', '}', '']

os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, 'w', encoding='utf-8', newline='\n') as f:
    f.write('\n'.join(lines))
print(f'{len(countries)} countries, {sum(len(p) for p in data.values())} provinces in {len(data)} countries -> {os.path.normpath(out)}')
